services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8888:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data: